logging:
    level:
        com: debug
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:mappers/**/*.xml
server:
    port: 8080
spring:
    aop:
        proxy-target-class: true
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root